export const ADD_CURRENT_TOPIC = 'ADD_CURRENT_TOPIC';
export const CLEAR_CURRENT_TOPIC = 'CLEAR_CURRENT_TOPIC';
export const UPDATE_CURRENT_TOPIC_AUTHOR = 'UPDATE_CURRENT_TOPIC_AUTHOR';
export const UPDATE_CURRENT_TOPIC_BODY = 'UPDATE_CURRENT_TOPIC_BODY';
export const UPDATE_CURRENT_TOPIC_CATEGORY = 'UPDATE_CURRENT_TOPIC_CATEGORY';
export const UPDATE_CURRENT_TOPIC_TITLE = 'UPDATE_CURRENT_TOPIC_TITLE';
