export const ADD_CURRENT_COMMENT = 'ADD_CURRENT_COMMENT';
export const CLEAR_CURRENT_COMMENT = 'CLEAR_CURRENT_COMMENT';
export const UPDATE_CURRENT_COMMENT_AUTHOR = 'UPDATE_CURRENT_COMMENT_AUTHOR';
export const UPDATE_CURRENT_COMMENT_BODY = 'UPDATE_CURRENT_COMMENT_BODY';
